SELECT
SPLIT_PART(TRANSACTION_CODE, '-',1) AS BANK,
DAYNAME(DATE(TRANSACTION_DATE, 'dd/mm/yyyy hh:mi:ss')) AS DATE,
CASE WHEN ONLINE_OR_IN_PERSON='2' THEN 'In-Person'
WHEN ONLINE_OR_IN_PERSON='1' THEN 'Online'
END AS ONLINE_OR_IN_PERSON,
COUNT (TRANSACTION_CODE)
FROM "TIL_PLAYGROUND"."PREPPIN_DATA_INPUTS"."PD2023_WK01"
GROUP BY TRANSACTION_DATE, ONLINE_OR_IN_PERSON, BANK;

SELECT 
SPLIT_PART(TRANSACTION_CODE, '-',1) AS BANK,
COUNT (TRANSACTION_CODE)
FROM TIL_PLAYGROUND.PREPPIN_DATA_INPUTS.PD2023_WK01
GROUP BY BANK;

SELECT CUSTOMER_CODE,
SPLIT_PART(TRANSACTION_CODE, '-',1) AS BANK,
COUNT (TRANSACTION_CODE)
FROM TIL_PLAYGROUND.PREPPIN_DATA_INPUTS.PD2023_WK01
GROUP BY BANK, CUSTOMER_CODE