SELECT B.*,
A.transaction_id,
REPLACE (SORT_CODE, '-', '') AS NEW_SORT_CODE,
'GB' AS COUNTRY_CODE,
TO_VARCHAR (ACCOUNT_NUMBER) AS NEW_ACCOUNT,
CONCAT(COUNTRY_CODE,CHECK_DIGITS,SWIFT_CODE,NEW_SORT_CODE,NEW_ACCOUNT) AS IBAN
FROM TIL_PLAYGROUND.PREPPIN_DATA_INPUTS.PD2023_WK02_TRANSACTIONS AS A
LEFT JOIN TIL_PLAYGROUND.PREPPIN_DATA_INPUTS.PD2023_WK02_SWIFT_CODES AS B
ON B.BANK=A.BANK;

SELECT A.transaction_id,
CONCAT('GB',CHECK_DIGITS,SWIFT_CODE,REPLACE (SORT_CODE, '-', ''),TO_VARCHAR (ACCOUNT_NUMBER)) AS IBAN
FROM TIL_PLAYGROUND.PREPPIN_DATA_INPUTS.PD2023_WK02_TRANSACTIONS AS A
LEFT JOIN TIL_PLAYGROUND.PREPPIN_DATA_INPUTS.PD2023_WK02_SWIFT_CODES AS B
ON B.BANK=A.BANK