SELECT *,
REPLACE (REPLACE (ONLINE_OR_IN_PERSON, '1','Online'), '2', 'In-Person') AS O_OR_IP,
QUARTER (TO_DATE (TRANSACTION_DATE, 'dd/mm/yyyy hh:mi:ss')) AS TRANSACTION_QUARTER
FROM TIL_PLAYGROUND.PREPPIN_DATA_INPUTS.PD2023_WK01
WHERE TRANSACTION_CODE LIKE 'DSB%';

SELECT 
sum (VALUE),
REPLACE (REPLACE (ONLINE_OR_IN_PERSON, '1','Online'), '2', 'In-Person') AS O_OR_IP,
QUARTER (TO_DATE (TRANSACTION_DATE, 'dd/mm/yyyy hh:mi:ss')) AS TRANSACTION_QUARTER
FROM TIL_PLAYGROUND.PREPPIN_DATA_INPUTS.PD2023_WK01
WHERE TRANSACTION_CODE LIKE 'DSB%'
GROUP BY O_OR_IP, TRANSACTION_QUARTER;

SELECT *,
REPLACE(QUARTER, 'Q', '') AS QN,
TO_DOUBLE (QN) AS QUARTER_N
FROM TIL_PLAYGROUND.PREPPIN_DATA_INPUTS.PD2023_WK03_TARGETS
UNPIVOT (TARGET_VALUE FOR QUARTER IN (Q1, Q2, Q3, Q4) );


SELECT
REPLACE(QUARTER, 'Q', '') AS QN,
TARGET_VALUE,
TO_DOUBLE (QN) AS QUARTER_N,
sum (VALUE),
REPLACE (REPLACE (B.ONLINE_OR_IN_PERSON, '1','Online'), '2', 'In-Person') AS O_OR_IP,
QUARTER (TO_DATE (TRANSACTION_DATE, 'dd/mm/yyyy hh:mi:ss')) AS TRANSACTION_QUARTER
FROM TIL_PLAYGROUND.PREPPIN_DATA_INPUTS.PD2023_WK03_TARGETS AS A
UNPIVOT (TARGET_VALUE FOR QUARTER IN (Q1, Q2, Q3, Q4) )
LEFT JOIN TIL_PLAYGROUND.PREPPIN_DATA_INPUTS.PD2023_WK01 AS B 
ON A.ONLINE_OR_IN_PERSON=O_OR_IP AND QUARTER_N=TRANSACTION_QUARTER
WHERE TRANSACTION_CODE LIKE 'DSB%'
GROUP BY O_OR_IP, TRANSACTION_QUARTER, A.ONLINE_OR_IN_PERSON, A.QUARTER, TARGET_VALUE;