
SELECT ID,
DATE(CONCAT (JOINING_DAY, ' 01', ' 2023'),'dd mm yyyy') AS JOINING_DATE,
DEMOGRAPHIC,
VALUE
FROM TIL_PLAYGROUND.PREPPIN_DATA_INPUTS.PD2023_WK04_JANUARY;


SELECT ID,
DATE(CONCAT (JOINING_DAY, ' 01', ' 2023'),'dd mm yyyy') AS JOINING_DATE,
DEMOGRAPHIC,
VALUE
FROM TIL_PLAYGROUND.PREPPIN_DATA_INPUTS.PD2023_WK04_JANUARY
UNION ALL
SELECT ID,
DATE(CONCAT (JOINING_DAY, ' 02', ' 2023'),'dd mm yyyy') AS JOINING_DATE,
DEMOGRAPHIC,
VALUE
FROM TIL_PLAYGROUND.PREPPIN_DATA_INPUTS.PD2023_WK04_FEBRUARY
UNION ALL
SELECT ID,
DATE(CONCAT (JOINING_DAY, ' 03', ' 2023'),'dd mm yyyy') AS JOINING_DATE,
DEMOGRAPHIC,
VALUE
FROM TIL_PLAYGROUND.PREPPIN_DATA_INPUTS.PD2023_WK04_MARCH
UNION ALL
SELECT ID,
DATE(CONCAT (JOINING_DAY, ' 04', ' 2023'),'dd mm yyyy') AS JOINING_DATE,
DEMOGRAPHIC,
VALUE
FROM TIL_PLAYGROUND.PREPPIN_DATA_INPUTS.PD2023_WK04_APRIL
UNION ALL
SELECT  ID,
DATE(CONCAT (JOINING_DAY, ' 05', ' 2023'),'dd mm yyyy') AS JOINING_DATE,
DEMOGRAPHIC,
VALUE
FROM TIL_PLAYGROUND.PREPPIN_DATA_INPUTS.PD2023_WK04_MAY
UNION ALL
SELECT ID,
DATE(CONCAT (JOINING_DAY, ' 06', ' 2023'),'dd mm yyyy') AS JOINING_DATE,
DEMOGRAPHIC,
VALUE
FROM TIL_PLAYGROUND.PREPPIN_DATA_INPUTS.PD2023_WK04_JUNE
UNION ALL
SELECT ID,
DATE(CONCAT (JOINING_DAY, ' 07', ' 2023'),'dd mm yyyy') AS JOINING_DATE,
DEMOGRAPHIC,
VALUE
FROM TIL_PLAYGROUND.PREPPIN_DATA_INPUTS.PD2023_WK04_JULY
UNION ALL
SELECT ID,
DATE(CONCAT (JOINING_DAY, ' 08', ' 2023'),'dd mm yyyy') AS JOINING_DATE,
DEMOGRAPHIIC,
VALUE
FROM TIL_PLAYGROUND.PREPPIN_DATA_INPUTS.PD2023_WK04_AUGUST
UNION ALL
SELECT ID,
DATE(CONCAT (JOINING_DAY, ' 09', ' 2023'),'dd mm yyyy') AS JOINING_DATE,
DEMOGRAPHIC,
VALUE
FROM TIL_PLAYGROUND.PREPPIN_DATA_INPUTS.PD2023_WK04_SEPTEMBER
UNION ALL
SELECT ID,
DATE(CONCAT (JOINING_DAY, ' 10', ' 2023'),'dd mm yyyy') AS JOINING_DATE,
DEMAGRAPHIC,
VALUE
FROM TIL_PLAYGROUND.PREPPIN_DATA_INPUTS.PD2023_WK04_OCTOBER
UNION ALL
SELECT ID,
DATE(CONCAT (JOINING_DAY, ' 11', ' 2023'),'dd mm yyyy') AS JOINING_DATE,
DEMOGRAPHIC,
VALUE
FROM TIL_PLAYGROUND.PREPPIN_DATA_INPUTS.PD2023_WK04_NOVEMBER
UNION ALL
SELECT ID,
DATE(CONCAT (JOINING_DAY, ' 12', ' 2023'),'dd mm yyyy') AS JOINING_DATE,
DEMOGRAPHIC,
VALUE
FROM TIL_PLAYGROUND.PREPPIN_DATA_INPUTS.PD2023_WK04_DECEMBER;


SELECT *,
DATE(CONCAT (JOINING_DAY, ' 01', ' 2023'),'dd mm yyyy') AS JOINING_DATE
FROM TIL_PLAYGROUND.PREPPIN_DATA_INPUTS.PD2023_WK04_JANUARY
PIVOT (MAX (VALUE) FOR DEMOGRAPHIC IN ('Ethnicity', 'Account Type', 'Date of Birth'))